const supabaseClient=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const loginCard=document.getElementById("loginCard"),dashboard=document.getElementById("dashboard"),loginForm=document.getElementById("loginForm"),loginMessage=document.getElementById("loginMessage"),adminMessage=document.getElementById("adminMessage"),requestsList=document.getElementById("requestsList"),logoutBtn=document.getElementById("logoutBtn"),refreshBtn=document.getElementById("refreshBtn");
function setMessage(el,text,type=""){el.className="message "+type;el.textContent=text;}
async function showDashboard(){loginCard.classList.add("hidden");dashboard.classList.remove("hidden");logoutBtn.classList.remove("hidden");await loadRequests();}
async function checkSession(){const{data}=await supabaseClient.auth.getSession();if(data.session)showDashboard();}
loginForm.addEventListener("submit",async(e)=>{e.preventDefault();setMessage(loginMessage,"Connexion...");const email=document.getElementById("email").value.trim(),password=document.getElementById("password").value;const{error}=await supabaseClient.auth.signInWithPassword({email,password});if(error){console.error(error);setMessage(loginMessage,"Email ou mot de passe incorrect.","error");return;}loginForm.reset();await showDashboard();});
logoutBtn.addEventListener("click",async()=>{await supabaseClient.auth.signOut();dashboard.classList.add("hidden");loginCard.classList.remove("hidden");logoutBtn.classList.add("hidden");requestsList.innerHTML="";});refreshBtn.addEventListener("click",loadRequests);
async function loadRequests(){setMessage(adminMessage,"Chargement des demandes...");const{data,error}=await supabaseClient.from("ticket_requests").select("*").order("created_at",{ascending:false});if(error){console.error(error);setMessage(adminMessage,"Impossible de charger les demandes.","error");return;}adminMessage.textContent="";if(!data||data.length===0){requestsList.innerHTML='<div class="empty">Aucune demande pour le moment.</div>';return;}requestsList.innerHTML=data.map(renderRequest).join("");document.querySelectorAll("[data-save]").forEach(b=>b.addEventListener("click",()=>updateRequest(b.dataset.save)));}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function renderRequest(i){const date=i.created_at?new Date(i.created_at).toLocaleString("fr-FR"):"-";return `<article class="request-card"><div class="request-top"><div><h3>${esc(i.reference||"Sans référence")}</h3><div class="request-meta">${esc(i.provider)} · ${esc(i.amount)} FCFA<br>Reçue le ${esc(date)}</div></div><span class="status ${esc(i.status)}">${esc(i.status)}</span></div><div class="request-details"><div><strong>Client :</strong> ${esc(i.customer_name)}</div><div><strong>Contact :</strong> ${esc(i.customer_contact)}</div><div><strong>Pays :</strong> ${esc(i.country)}</div><div><strong>Date d'achat :</strong> ${esc(i.purchase_date||"-")}</div><div><strong>Référence ticket :</strong> ${esc(i.ticket_reference||"-")}</div><div><strong>Note :</strong> ${esc(i.notes||"-")}</div></div><div class="request-actions"><select id="status-${i.id}">${["pending","processing","verified","rejected"].map(s=>`<option value="${s}" ${i.status===s?"selected":""}>${s}</option>`).join("")}</select><textarea id="result-${i.id}" rows="3" placeholder="Message / résultat à transmettre">${esc(i.result_message||"")}</textarea><button class="small-button" data-save="${i.id}">Enregistrer le résultat</button></div></article>`;}
async function updateRequest(id){const status=document.getElementById("status-"+id).value,result_message=document.getElementById("result-"+id).value.trim()||null;setMessage(adminMessage,"Enregistrement...");const{error}=await supabaseClient.from("ticket_requests").update({status,result_message}).eq("id",id);if(error){console.error(error);setMessage(adminMessage,"Erreur lors de l'enregistrement.","error");return;}setMessage(adminMessage,"✓ Résultat enregistré.","success");await loadRequests();}
checkSession();
